import type { Metadata } from "next";
import { Mulish } from "next/font/google";
// @ts-ignore
import "./globals.css";
import Navbar from "@/components/containers/navbar/Navbar";

const mulishFont = Mulish({
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulishFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
